# Generated by Django 2.2.6 on 2019-11-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Binding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('detail', models.CharField(blank=True, max_length=1024)),
                ('price', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='binding/')),
            ],
        ),
        migrations.CreateModel(
            name='files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='doc/')),
                ('size', models.CharField(blank=True, max_length=255)),
                ('F_type', models.CharField(blank=True, max_length=255)),
                ('pages', models.CharField(blank=True, max_length=255)),
                ('user_id', models.IntegerField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
