# Generated by Django 2.2.6 on 2019-11-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='user_id',
            field=models.IntegerField(blank=True, max_length=15),
        ),
    ]
