# Generated by Django 2.2.6 on 2019-11-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20191113_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='user_id',
            field=models.IntegerField(blank=True),
        ),
    ]
