# Generated by Django 2.2.6 on 2019-11-17 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20191114_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='files',
            options={'verbose_name_plural': 'files'},
        ),
        migrations.AlterField(
            model_name='binding',
            name='image',
            field=models.ImageField(upload_to='documents/media/binding/'),
        ),
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(upload_to='documents/media/doc/'),
        ),
        migrations.AlterModelTable(
            name='files',
            table='files',
        ),
    ]
