# Generated by Django 2.2.6 on 2019-11-14 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agrement',
            options={'verbose_name_plural': 'Agrement'},
        ),
        migrations.AlterModelOptions(
            name='shops',
            options={'verbose_name_plural': 'shops'},
        ),
        migrations.AddField(
            model_name='agrement',
            name='Shop_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Shops'),
        ),
        migrations.AlterField(
            model_name='agrement',
            name='agrement_details',
            field=models.CharField(max_length=4096, verbose_name='Agrement'),
        ),
        migrations.AlterField(
            model_name='shops',
            name='Shop_name',
            field=models.CharField(max_length=100, verbose_name='Shop Name'),
        ),
        migrations.AlterField(
            model_name='shops',
            name='address',
            field=models.FileField(upload_to='pictures/', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='shops',
            name='city',
            field=models.CharField(max_length=250, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='shops',
            name='location',
            field=models.CharField(max_length=250, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='shops',
            name='opperator_name',
            field=models.CharField(max_length=50, verbose_name='Opperator Name'),
        ),
        migrations.AlterModelTable(
            name='agrement',
            table='Agrement',
        ),
    ]
