# Generated by Django 2.2.6 on 2019-11-14 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20191114_1558'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agrement',
            table='agrement',
        ),
    ]
