# Generated by Django 2.2.6 on 2019-11-14 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20191114_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agrement',
            old_name='Shop_id',
            new_name='Shop',
        ),
    ]
